#!/bin/zsh
# execute after all the plugin config stuff
if [ -d $zd -a -r $zd/post ]; then source $zd/post; fi

# zshrc.d
if [ -d $zd ]; then
    for f in $zd/*.zrc
    do
        source $f
    done
fi

# local zshrc
if [ -r ~/.zshrc.local ]; then source ~/.zshrc.local; fi
