#!/bin/zsh
# execute after all the plugin config stuff
if [ -d $zd -a -r $zd/post ]; then source $zd/post; fi

# zshrc.d
unsetopt NOMATCH #don't report an error if no zrc files are found
if [ -d $zd ]; then
    for f in $zd/*.zrc
    do
        [ -r $f ] && source $f
    done
fi
setopt NOMATCH

# local zshrc
if [ -d $zd -a -r $zd/zshrc.local ]; then
    source $zd/zshrc.local
elif [ -r ${ZDOTDIR:-$HOME}/.zshrc.local ]; then
    source ${ZDOTDIR:-$HOME}/.zshrc.local
elif [ -r ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi
