#!/bin/zsh
# execute after all the plugin config stuff

# local zshrc
if [ -r ~/.zshrc.local ]; then source ~/.zshrc.local; fi

# zshrc.d
if [ -d ~/.zshrc.d ]; then
    for f in ~/.zshrc.d/*.rc
    do
        source $f
    done
fi
