#!/bin/zsh
# execute before any plugin config stuff
if [ -d $zd -a -r $zd/pre ]; then source $zd/pre; fi

#upgrade function, does not to submodules: they should manage themselves
function toast-zsh-upgrade { git -C $zshd pull }

#source ~/.zshrc again, even after you've changed the symlink (but haven't restarted your shell yet)
function toast-zsh-resource { source $zrc }

#source ~/.zshrc, naive, so won't verify if it exists, or is the same, etc
function toast-zsh-source { source ~/.zshrc }

#easy/fast switching between different RCs, don't forget to toast-zsh-source afterwards
function toast-zsh-switch { ln -sf $zshd/$1.zrc ~/.zshrc }
